---
dependencies: []

galaxy_info:
  author: darthkoax
  description: Installation for fzf on airgapped UNIX/Linux.
  min_ansible_version: 2.2
  platforms:
    - name: GenericUNIX
      versions:
        - all
        - any
  galaxy_tags:
    - development
    - system
    - configuration
