---
roles:
  - name: geerlingguy.dotfiles
    src: https://github.com/geerlingguy/ansible-role-dotfiles/archive/refs/tags/1.2.1.tar.gz
  - name: fubarhouse.golang
    src:  https://github.com/fubarhouse/ansible-role-golang/archive/refs/tags/2.10.0.tar.gz
  - name: darthkoax.fzf.role
    src: https://github.com/DarthKoax/darthkoax.fzf.role/archive/refs/tags/darthkoax.fzf.role.1.0.0.tar.gz
  - name: darthkoax.neovim.role
    src: https://github.com/DarthKoax/darthkoax.neovim.role/archive/refs/tags/darthkoax.nvim.role.v1.1.0.tar.gz
    
