---
roles:
  - name: geerlingguy.dotfiles
    src: https://github.com/geerlingguy/dotfiles/archive/refs/tags/1.1.0.tar.gz
  - name: fubarhouse.golang
    src:  https://github.com/fubarhouse/ansible-role-golang/archive/refs/tags/2.10.0.tar.gz
    
    