---
# - name: Include OS-specific variables
#   debug:
#     msg: "./roles/darthkoax.installation/tasks/{{ ansible_os_family }}.yml"
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install in fzf for Airgapped env
  include_tasks: "fzf.yml"
  when: install_fzf

- name: Install in neovim for Airgapped env
  include_tasks: "neovim.yml"
  when: install_neovim

