---
# - name: Include OS-specific variables
#   debug:
#     msg: "./roles/darthkoax.installation/tasks/{{ ansible_os_family }}.yml"
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"
