---
- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 3600

- name: Install necessary packages
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add Docker's stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
