---

- name: "debug"
  debug:
    msg: "ansible_distribution: {{ ansible_distribution }}"

- name: Check if the system is WSL
  command: grep -qi wsl /proc/version
  changed_when: false
  register: wsl_check
  ignore_errors: true

- name: Set is_wsl fact
  set_fact: 
    is_wsl: "{{ wsl_check.rc == 0 }}"

- name: Install Docker on Debian
  include: debian.yml
  when: ansible_os_family == "Debian" and not is_wsl

- name: Install Podman on RedHat
  include: redhat.yml
  when: ansible_os_family == "RedHat" and not is_wsl

- name: Warning for WSL systems
  debug:
    msg: "Container runtimes installation is not supported on WSL. Skipping."
  when: is_wsl