---
applications: 
 - curl


fzf_repo: "git@github.com:junegunn/fzf.git"
fzf_binary: https://github.com/junegunn/fzf/releases/download/0.45.0/fzf-0.45.0-linux_amd64.tar.gz
fzf_scripts: 
 - key-bindings.bash
 - completion.bash 
fzf_additional_bins: 
 - fzf-tmux
fzf_bin_destination: /usr/local/bin

neovim_appimage_url: https://github.com/neovim/neovim/releases/download/v0.9.5/
neovim_binary_name: nvim.appimage
local_neovim_dir: ~/.local/share/nvim
config_neovim_dir: ~/.config/nvim

neovim_dependencies: 

  - fuse 
  - fuse-libs


neovim_plugins:
  - name: "Comment.nvim"
    repo: "https://github.com/numToStr/Comment.nvim.git"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/plugins/start/Comment.nvim"
  - name: "neo-tree"
    repo: "https://github.com/nvim-neo-tree/neo-tree.nvim.git"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/plugins/start/neo-tree"
  - name: "plenary.nvim"
    repo: "https://github.com/nvim-lua/plenary.nvim.git"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/plugins/start/plenary.nvim"
  - name: "nui.nvim"
    repo: "https://github.com/MunifTanjim/nui.nvim.git"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/plugins/start/nui.nvim"

