---
git_repo_source: https://github.com
git_binary_source: https://github.com

install_neovim: true
install_fzf: true

applications:
  - curl

fzf_repo: "{{git_repo_source}}/junegunn/fzf.git"
fzf_binary: "{{git_binary_source}}/junegunn/fzf/releases/download/0.45.0/fzf-0.45.0-linux_amd64.tar.gz"
fzf_scripts:
  - key-bindings.bash
  - completion.bash
fzf_additional_bins:
  - fzf-tmux
fzf_bin_destination: /usr/local/bin

neovim_appimage_url: "{{git_binary_source}}/neovim/neovim/releases/download/v0.9.5/"
neovim_binary_name: nvim.appimage
local_neovim_dir: ~/.local/share/nvim
config_neovim_dir: ~/.config/nvim

neovim_dependencies:
  - fuse
  - fuse-libs


nvim_custom_project: darthkoax
nvim_lazy_nvim_repo: "{{git_repo_source}}/folke/lazy.nvim.git"
nvim_lazy_plugins_install: |
  "{{git_repo_source}}/numToStr/Comment.nvim.git",
  {
    "{{git_repo_source}}/nvim-neo-tree/neo-tree.nvim.git",
    branch = "v3.x",
    dependencies = {
      "{{git_repo_source}}/nvim-lua/plenary.nvim.git",
      "{{git_repo_source}}/nvim-tree/nvim-web-devicons.git",
      "{{git_repo_source}}/MunifTanjim/nui.nvim.git",
    }
  },
  {
    "{{git_repo_source}}/folke/which-key.nvim.git",
    event = "VeryLazy",
    init = function()
      vim.o.timeout = true
      vim.o.timeoutlen = 300
    end,
    opts = {
      -- your configuration comes here
      -- or leave it empty to use the default settings
      -- refer to the configuration section below
    }
  },
  {
    '{{git_repo_source}}/nvim-telescope/telescope.nvim.git', 
    tag = '0.1.5',
    dependencies = { 
      '{{git_repo_source}}/nvim-lua/plenary.nvim.git' 
    }
  },
  { 
    '{{git_repo_source}}/catppuccin/nvim.git', 
    name = "catppuccin", 
    priority = 1000 
  },
  {
  "{{git_repo_source}}/folke/noice.nvim.git",
  event = "VeryLazy",
  opts = {
    -- add any options here
  },
  dependencies = {
    -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
    "{{git_repo_source}}/MunifTanjim/nui.nvim.git",
    -- OPTIONAL:
    "{{git_repo_source}}/rcarriga/nvim-notify.git",
  }
  },
  {
    '{{git_repo_source}}/akinsho/bufferline.nvim.git', 
    version = "*", 
    dependencies = '{{git_repo_source}}/nvim-tree/nvim-web-devicons.git'
  }
