---
install_neovim: true
applications:
  - curl

fzf_repo: "git@github.com:junegunn/fzf.git"
fzf_binary: https://github.com/junegunn/fzf/releases/download/0.45.0/fzf-0.45.0-linux_amd64.tar.gz
fzf_scripts:
  - key-bindings.bash
  - completion.bash
fzf_additional_bins:
  - fzf-tmux
fzf_bin_destination: /usr/local/bin

neovim_appimage_url: https://github.com/neovim/neovim/releases/download/v0.9.5/
neovim_binary_name: nvim.appimage
local_neovim_dir: ~/.local/share/nvim
config_neovim_dir: ~/.config/nvim

neovim_dependencies:
  - fuse
  - fuse-libs

nvim_custom_project: darthkoax
nvim_lazy_nvim_repo: "https://github.com/folke/lazy.nvim.git"
nvim_lazy_plugins_install: |
  "https://github.com/numToStr/Comment.nvim.git",
  {
    "https://github.com/nvim-neo-tree/neo-tree.nvim.git",
    branch = "v3.x",
    dependencies = {
      "https://github.com/nvim-lua/plenary.nvim.git",
      "https://github.com/nvim-tree/nvim-web-devicons.git",
      "https://github.com/MunifTanjim/nui.nvim.git",
    }
  },
  {
    "https://github.com/folke/which-key.nvim.git",
    event = "VeryLazy",
    init = function()
      vim.o.timeout = true
      vim.o.timeoutlen = 300
    end,
    opts = {
      -- your configuration comes here
      -- or leave it empty to use the default settings
      -- refer to the configuration section below
    }
  },
  {
    'https://github.com/nvim-telescope/telescope.nvim.git', 
    tag = '0.1.5',
    dependencies = { 
      'https://github.com/nvim-lua/plenary.nvim.git' 
    }
  }
